In [13]:
import pandas as pd

df = pd.read_csv("students.csv")

print(df)

      Name  Marks       City
0   Sujeet     90   Varanasi
1    Rahul     85      Delhi
2     Aman     88    Lucknow
3    Rohan     78   Dehradun
4   Saurbh     80  Rishikesh
5   Mayank     75  Prayagraj
6     raju     60      noida
7  pratham     80   haridwar

In [19]:
df.head()

     Name  Marks       City
0  Sujeet     90   Varanasi
1   Rahul     85      Delhi
2    Aman     88    Lucknow
3   Rohan     78   Dehradun
4  Saurbh     80  Rishikesh

In [16]:
df.tail()

      Name  Marks       City
3    Rohan     78   Dehradun
4   Saurbh     80  Rishikesh
5   Mayank     75  Prayagraj
6     raju     60      noida
7  pratham     80   haridwar

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      str
 1   Marks   8 non-null      int64
 2   City    8 non-null      str
dtypes: int64(1), str(2)
memory usage: 426.0 bytes

In [18]:
df.describe()

           Marks
count   8.000000
mean   79.500000
std     9.380832
min    60.000000
25%    77.250000
50%    80.000000
75%    85.750000
max    90.000000